"""Add refresh tokens table

Revision ID: 41aecffa0c89
Revises: 
Create Date: 2026-03-15 20:19:47.662600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41aecffa0c89'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Use IF NOT EXISTS to avoid errors if table was pre-created by SQLAlchemy
    op.execute("""
        CREATE TABLE IF NOT EXISTS refresh_tokens (
            id BIGSERIAL NOT NULL,
            id_usuario BIGINT NOT NULL,
            token_hash VARCHAR(255) NOT NULL,
            revoked BOOLEAN DEFAULT 'false',
            expires_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
            created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now(),
            PRIMARY KEY (id),
            FOREIGN KEY(id_usuario) REFERENCES usuarios (id_usuario)
        )
    """)
    op.execute("CREATE INDEX IF NOT EXISTS ix_refresh_tokens_id ON refresh_tokens (id)")
    op.execute("CREATE UNIQUE INDEX IF NOT EXISTS ix_refresh_tokens_token_hash ON refresh_tokens (token_hash)")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    # ### end Alembic commands ###
